import localFont from "next/font/local";
import "./globals.css";
import {Outfit} from "next/font/google"

const Outfit_init = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-outfit'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={Outfit_init.variable}
      >
        {children}
      </body>
    </html>
  );
}
